src/objects/Test__c.object
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TestExecution__c.object
<CustomObject>
    <fields>
        <fullName>Browser__c</fullName>
        <label>Browser</label>
        <picklist>
            <picklistValues>
                <fullName>firefox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iexplore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>safari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>opera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>googlechrome</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InProgress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>InProgress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OS__c</fullName>
        <label>OS</label>
        <picklist>
            <picklistValues>
                <fullName>Linux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windows 2003</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>tearDown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Session_Id__c</fullName>
        <label>Session Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>TestExecutions</relationshipLabel>
        <relationshipName>TestExecutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <picklist>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TestExecution</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>TestExecution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TestExecutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestExecutionManager.cls
/**
*  This class coordinates the execution of the different steps that make up a Test
*  We need to coordinate these steps because they are executed using @future methods
*  The reasoning behind @future is that we need to execute callouts to Sauce Labs
*/
global class TestExecutionManager implements Schedulable, ITestExecutionManager{
      
    static ITest getTest(String testName, String os, String browser, String version) {                          
    /** This method provides the mapping between the Test as a record in salesforce.com
        and the test as an executable unit in salesforce.com. Use the following patern
        to make sure your tests are scheduled and executed correctly:
    
        if(testName.equalsIgnoreCase('Test Demo'))
            return new TestDemo(os, browser, version);  
         else
    */
             return null;
    }       
   
   global void execute(SchedulableContext sc) {   
       for(TestExecution__c sem:   [select Test__r.name, name, phase__c, session_id__c, inProgress__c, 
       os__c, browser__c, version__c
        from TestExecution__c where inProgress__c = false and phase__c != 'Done' and phase__c != 'Error' and phase__c != null FOR UPDATE]) {          
           TestExecutionManager.inFuture(sem.phase__c, sem.session_id__c, sem.Test__r.name, sem.name, sem.os__c, sem.browser__c, sem.version__c);
           sem.inProgress__c = true;
           update(sem);
       }   
   }
   
   @future (callout=true)
   global static void inFuture(String phase, String sessionId, String testName, String testCase, String os, String browser, String version) {
       ITest test = TestExecutionManager.getTest(testName, os, browser, version);
       TestExecutioner te = new TestExecutioner();
       te.run(test, phase, sessionId, testName, testCase, os, browser, version);       
   }
    
      
   public static void schedule() {
       TestExecutionManager s = new TestExecutionManager();
       integer minute = Datetime.now().minute();
       for(integer i=0;i<5;i++) {
           integer nextMinute = Math.mod((minute + i), 60);
           system.schedule('Test Execution Manager ' + i, '0 ' + nextMinute + ' * * * ?', s);
           system.schedule('Test Execution Manager ' + i + '.5', '30 ' + nextMinute + ' * * * ?', s);           
       }

   }
   
   public static void unschedule() {
 		for(CronTrigger ct: [select id from CronTrigger]) {
 			System.abortJob(ct.id);
 		}   		
   }    
}