trunk/src/objects/TestCloudConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Login_URL__c</fullName>
        <label>SFDC Login URL</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sauce_Access_Key__c</fullName>
        <label>Sauce Access Key</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sauce_Username__c</fullName>
        <label>Sauce Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selenium_Proxy_Port__c</fullName>
        <label>Selenium Proxy Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selenium_Proxy_URL__c</fullName>
        <label>Selenium Proxy URL</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Test Cloud Config</label>
</CustomObject>

src/classes/SauceTest.cls
/**
* abstract implementation of a test that is going to run on sauce labs
*/
global abstract class SauceTest implements ITest{
    
    global SauceTest (String os, String browser, String version) {
        this.os = os;
        this.browser = browser;
        this.version = version;
    }    
                
    global String setUp() {
        selenium1.DefaultSelenium s = makeSelenium();        
        String sessionId = s.start();
        login(s);
        return sessionId;                    
    }

    global abstract ITestStep getStep(integer step);

    global void tearDown(String sessionId) {
        selenium1.DefaultSelenium s = getSelenium(sessionId);        
        s.stop();       
    }

    global selenium1.DefaultSelenium getSelenium(String sessionId) {
        selenium1.DefaultSelenium s = makeSelenium();
        s.start(sessionId);
        return s;                           
    }

    public void login(selenium1.DefaultSelenium s) {
        s.open('/');
        s.type('username', TestCloudConfig__c.getInstance().username__c);
        s.type('password', TestCloudConfig__c.getInstance().password__c);
        s.clickAndWait('css=input.loginButton');    
    }
        
    public virtual selenium1.DefaultSelenium makeSelenium() {
        selenium1.DefaultSelenium s = new selenium1.DefaultSelenium(TestCloudConfig__c.getInstance().sfdc_login_url__c
        , TestCloudConfig__c.getInstance().selenium_proxy_url__c, TestCloudConfig__c.getInstance().selenium_proxy_port__c.intValue(), 
        getConnectionString());
        return s;
    }

    public SauceTest () {
        this('Linux', 'firefox', '3.');
    }

    private String getConnectionString() {
       return '{\"username\": \"' + TestCloudConfig__c.getInstance().sauce_username__c + 
       '\", \"access-key\": \"' + TestCloudConfig__c.getInstance().sauce_access_key__c + 
       '\", \"os\": \"' + os + '\", \"browser\": \"' + browser + '\", \"browser-version\": \"' + version + '\", \"max-duration\": \"300\"}';
    }

    private String os;
    private String browser;
    private String version;

}